version: "3.4"

services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: minicommerce
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

  redis:
    image: redis:latest
    ports:
      - "6320:6379"
