version: "3.4"

services:

  postgres:
    image: postgres:13.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: minicommerce
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
