version: "3.4"

services:

  mysql:
    # Apple M1 user needs to pull image manually:
    # docker pull --platform linux/x86_64 mysql:8.0.23
    image: mysql:8.0.23
    ports:
      - 3326:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_USER: dbuser
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: commerce
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
